#!/bin/bash


set -e
set -o pipefail


if [[ ! -f "$1" ]]; then
	echo 'File argument is required.'
	exit 1
fi


base=$(basename "$1")
before=$(find "$base" -maxdepth 1)


filename="$1"
filename="./${filename%.*}"


# extract to a directory named "file [minus] extension"
extract_to_directory() {
	wrapper_dir="$filename"
	count=0

	# directory exists? keep incrementing count and adding it to the end of the name
	while [ -d "$wrapper_dir" ]; do
		let "count += 1"
		wrapper_dir="${filename}.${count}"
		#echo "$wrapper_dir"
	done

	7z x "$1" -o"$wrapper_dir" &>/dev/null

	# check wrapper_dir contents for just one folder; move contents up one dir and remove the single dir
	dirs=$(find "$wrapper_dir" -mindepth 1 -maxdepth 1 -type d | wc -l)
	files=$(find "$wrapper_dir" -mindepth 1 -maxdepth 1 -type f | wc -l)
	if [ "$dirs" == '1' ] && [ "$files" == '0' ]; then
		inner_dir=$(find "$wrapper_dir" -mindepth 1 -maxdepth 1 -type d)
		find "$inner_dir" -mindepth 1 -maxdepth 1 | xargs mv -iv -t "$wrapper_dir" &>/dev/null
		rmdir "$inner_dir"
	fi

	echo "$(pwd)/$(basename $1) => $(pwd)/$(basename $wrapper_dir)/"
}


case $1 in
	*.tar.bz2) tar -xjf $1 ;;
	*.tar.gz) tar -xzf $1 ;;
	*) extract_to_directory $1 ;;

	(*.tar.gz|*.tgz) tar -xzf "$1" ;;
	(*.tar.bz2|*.tbz|*.tbz2) tar -xjf "$1" ;;
	(*.tar.xz|*.txz) tar --xz --help &> /dev/null \
   && tar --xz -xvf "$1" \
   || xzcat "$1" | tar xvf - ;;
   (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null \
   && tar --lzma -xvf "$1" \
   || lzcat "$1" | tar xvf - ;;
   (*.tar) tar xvf "$1" ;;
   (*.gz) gunzip "$1" ;;
   (*.bz2) bunzip2 "$1" ;;
   (*.xz) unxz "$1" ;;
   (*.lzma) unlzma "$1" ;;
   (*.Z) uncompress "$1" ;;
   (*.zip) unzip "$1" -d $extract_dir ;;
   (*.rar) unrar x -ad "$1" ;;
   (*.7z) 7za x "$1" ;;
   (*.deb)
   esac
