#!/bin/bash

find . -maxdepth 4 -name '.git' -type d -print0 | sort -z | \
while IFS= read -r -d $'\0' dir; do
	pushd "$(realpath "$dir/..")" &>/dev/null
	printf "$(pwd):\n"
	modtime
	git s
	echo ''
	popd &>/dev/null
done
