#!/bin/bash

set -e


assume_unchanged="$(git ls-files -v | grep -E '^h' | perl -pe 's/^h\s(.*)/\1/')"

output=""
if script -q -c 'pwd' /dev/null &>/dev/null; then
	output=$(script -q -c "command git status "$@"" /dev/null)
elif script -q /dev/null 'pwd' &>/dev/null; then
	output=$(script -q /dev/null command git status "$@")
fi

UTR=$(git config --get-color color.status.untracked 'red')
RESET=$(git config --get-color '' 'reset')

if [[ -n $assume_unchanged ]]; then
	echo "$output"
	echo "#"
	echo "# Assume-unchanged files:"
	echo '#   (use "git update-index --no-assume-unchanged <file>" to start tracking)'
	echo "#"
	for file in "$assume_unchanged"; do
		echo "#       $UTR$file$RESET"
	done
else
	echo "$output"
fi
