#!/bin/bash

set -e

program=$(basename $0)
DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


version() {
    echo "$program 0.1.0"
}


usage() {
    version
    cat <<_EOF
Usage: $program COMMAND [args]

Commands:
  update                # Retrieve list of updated packages
  outdated              # List packages that have an updated version available
  installed [<package>] # List installed packages matching a pattern
  files <package>       # List all files provided by a package
  search <package>      # Search for a package in all available packages
  info <package>        # Print info for package
  deplist <package>     # List dependencies for package
  whatprovides <file>   # List packages which provide the given file
  install <package>     # Install new packages
  reinstall <package>   # Reinstall packages
  upgrade [<package>]   # Install newer version of outdated packages
  remove <package>      # Remove packages
  purge <package>       # Remove packages and config files
  clean                 # Erase downloaded archive files
  autoclean             # Erase old downloaded archive files
  commands              # List available commands
_EOF
}


commands() {
    local commands='update outdated installed files search info depends install reinstall upgrade remove purge whatprovides clean autoclean'
    for command in $(echo $commands); do
        echo $command
    done
}


command_not_found() {
    local command=$1
    echo "$program: Could not find command '$command'."
    echo "See '$program help' for more information on a specific command"
    exit 1
}


main() {
    local command=$1
    shift

    case $command in
        help|--help|-h)
            usage
            exit 0
            ;;
        command|commands)
            commands
            exit 0
            ;;
        completion)
            cat "$DIRNAME/p-completion.sh"
            exit 0
            ;;
    esac

    if which apt-get &>/dev/null; then

        case $command in
            search)
                apt-cache search "$@"
                ;;
            install)
                sudo apt-get install "$@"
                ;;
            reinstall)
                sudo apt-get install --reinstall "$@"
                ;;
            update)
                sudo apt-get update "$@"
                ;;
            upgrade)
                sudo apt-get upgrade "$@"
                ;;
            remove)
                sudo apt-get remove "$@"
                ;;
            purge)
                sudo apt-get --purge remove "$@"
                ;;
            info)
                apt-cache show "$@"
                ;;
            files)
                dpkg-query -L "$@"
                ;;
            deplist)
                apt-cache depends "$@"
                ;;
            whatprovides)
                apt-file list --fixed-string "$1" | grep "/$1\$"
                ;;
            installed)
                dpkg-query -l "$1*" | grep '^ii'
                ;;
            outdated)
                apt-get upgrade -s | grep Inst
                ;;
            clean)
                sudo apt-get clean
                ;;
            autoclean)
                sudo apt-get autoclean
                ;;
            *)
                command_not_found $command
                ;;
        esac

    elif which brew &>/dev/null; then

        case $command in
            search)
                s_name="$(brew search "$@")"
                s_desc="$(brew desc -s "$@")"
                if [[ -n "$s_name" ]]; then
                    echo "$s_name"
                fi
                if [[ -n "$s_name" && -n "$s_desc" ]]; then
                    echo '---'
                fi
                if [[ -n "$s_desc" ]]; then
                    echo "$s_desc"
                fi
                ;;
            install)
                brew install "$@"
                ;;
            reinstall)
                echo "Not found: '$command', see https://github.com/mxcl/homebrew/issues/12511"
                ;;
            update)
                brew update
                ;;
            upgrade)
                brew upgrade "$@"
                ;;
            remove)
                brew remove "$@"
                ;;
            purge)
                echo "Not found: '$command', use 'remove'"
                ;;
            info)
                brew info "$@"
                ;;
            files)
                brew list --verbose "$@"
                ;;
            deplist)
                brew deps "$@"
                ;;
            whatprovides)
                echo "Not found: '$command'"
                ;;
            installed)
                echo "Not found: '$command'"
                ;;
            outdated)
                brew outdated "$@"
                ;;
            clean)
                echo "Not found: '$command', use 'autoclean'"
                ;;
            autoclean)
                brew cleanup
                ;;
            *)
                command_not_found $command
                ;;
        esac

    elif which yum &>/dev/null; then

        case $command in
            search)
                s_name="$(sudo yum search all --showduplicates --debuglevel=0 --errorlevel=0 "$@")"
                s_desc="$(sudo yum list --showduplicates --debuglevel=0 --errorlevel=0 "$@")"
                if [[ -n "$s_name" ]]; then
                    echo "$s_name"
                fi
                if [[ -n "$s_name" && -n "$s_desc" ]]; then
                    echo '---'
                fi
                if [[ -n "$s_desc" ]]; then
                    echo "$s_desc"
                fi
                ;;
            install)
                sudo yum install "$@"
                ;;
            reinstall)
                sudo yum reinstall "$@"
                ;;
            update)
                yum check-update
                ;;
            upgrade)
                sudo yum update "$@"
                ;;
            remove)
                sudo yum erase "$@"
                ;;
            purge)
                echo "Not found: '$command', use 'remove'"
                ;;
            info)
                sudo yum info --debuglevel=0 --errorlevel=0 "$@"
                ;;
            files)
                rpm -ql "$@"
                ;;
            deplist)
                yum deplist "$@"
                ;;
            whatprovides)
                yum whatprovides "$@"
                ;;
            installed)
                rpm -qa
                ;;
            outdated)
                yum check-update
                ;;
            clean)
                sudo yum clean
                ;;
            autoclean)
                sudo yum clean
                ;;
            *)
                command_not_found $command
                ;;
        esac

    elif which apt-cyg &>/dev/null; then

        case $command in
            search)
                apt-cyg find --noupdate "$@"
                ;;
            install)
                apt-cyg install --noupdate "$@"
                ;;
            reinstall)
                command_not_found $command
                ;;
            update)
                apt-cyg update
                ;;
            upgrade)
                command_not_found $command
                ;;
            remove)
                apt-cyg remove --noupdate "$@"
                ;;
            purge)
                echo "Not found: '$command', use 'remove'"
                ;;
            info)
                apt-cyg describe "$@" --noupdate | sed -n "/^$1$/,/^$/{p}"
                ;;
            files)
                command_not_found $command
                ;;
            deplist)
                p info "$@" | grep '^requires:' | sed 's/^requires: \(.*\)/\1/' | sed 's/ /\n/g' | sort
                ;;
            whatprovides)
                apt-cyg packageof --noupdate "$@"
                ;;
            installed)
                apt-cyg show
                ;;
            outdated)
                command_not_found $command
                ;;
            clean)
                command_not_found $command
                ;;
            autoclean)
                command_not_found $command
                ;;
            *)
                command_not_found $command
                ;;
        esac

    fi
}


main "$@"
