#!/bin/bash

set -eo pipefail

DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Dropbox & btsync: increase max watched files
max_watches="1000000"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    if [[ "$(sysctl fs.inotify.max_user_watches)" != "fs.inotify.max_user_watches = $max_watches" ]]; then
        echo "fs.inotify.max_user_watches = $max_watches" | sudo tee -a /etc/sysctl.conf
        # apply new limit right now
        sudo sysctl -p
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    launchctl limit maxfiles "$max_watches" "$max_watches"
fi

# add a NOPASSWD line to sudoers file for the current user
"$DIRNAME/setup-visudo-helper"

# Ubuntu: make bash the default shell (for my complicated .profile script)
if [[ "$(readlink /bin/sh)" == "/bin/dash" ]]; then
    sudo ln -sf /bin/bash /bin/sh
fi
